Repository AY2425S1-CS2113-W12-2/tp, pull requests merged in 2024-10, with the labels that each got.

#22 Add Parser Package and Class
  docs/AboutUs.md
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#20 Add Student and University Package
  .gitignore
  src/main/java/student/Student.java
  src/main/java/university/University.java
  src/main/java/university/UniversityRepository.java
Labels: priority.High

#23 Add Command Package and Classes
  src/main/java/Command/AddCommand.java
  src/main/java/Command/AllocateCommand.java
  src/main/java/Command/Command.java
  src/main/java/Command/DeleteCommand.java
  src/main/java/Command/ExitCommand.java
  src/main/java/Command/GenerateCommand.java
  src/main/java/Command/HelpCommand.java
  src/main/java/Command/ListCommand.java
  src/main/java/parser/Parser.java
  src/main/java/ui/UI.java
Labels: priority.High

#26 Add StudentList Package and Class
  build.gradle
  src/main/java/Command/AddCommand.java
  src/main/java/Command/AllocateCommand.java
  src/main/java/Command/Command.java
  src/main/java/Command/DeleteCommand.java
  src/main/java/Command/ExitCommand.java
  src/main/java/Command/GenerateCommand.java
  src/main/java/Command/HelpCommand.java
  src/main/java/Command/ListCommand.java
  src/main/java/command/AddCommand.java
  src/main/java/command/AllocateCommand.java
  src/main/java/command/Command.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/ExitCommand.java
  src/main/java/command/GenerateCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/command/ListCommand.java
  src/main/java/parser/Parser.java
  src/main/java/seedu/duke/FindOurSEP.java
  src/main/java/student/Student.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/UI.java
  src/main/java/university/UniversityRepository.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#30 UI: Implement print tables and messages
  build.gradle
  src/main/java/command/AddCommand.java
  src/main/java/command/AllocateCommand.java
  src/main/java/command/Command.java
  src/main/java/command/DeleteCommand.java
  src/main/java/command/ExitCommand.java
  src/main/java/command/GenerateCommand.java
  src/main/java/command/HelpCommand.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/parser/Parser.java
  src/main/java/student/Student.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/Messages.java
  src/main/java/ui/UI.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High, severity.High

#32 Allocator: Add sorting strategies, copy constructors, and allocator package
  src/main/java/allocator/Allocator.java
  src/main/java/student/Student.java
  src/main/java/studentlist/StudentList.java
Labels: priority.High

#35 Integrate allocate algorithm into allocate command
  src/main/java/command/AllocateCommand.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/UI.java
Labels: type.Bug, priority.High, severity.High

#37 Add new unknown command
  src/main/java/command/UnknownCommand.java
  src/main/java/parser/Parser.java
Labels: priority.High

#40 Add Exception Packages and classes, Add JavaDoc comments
  src/main/java/command/AddCommand.java
  src/main/java/command/DeleteCommand.java
  src/main/java/exceptions/SEPDuplicateException.java
  src/main/java/exceptions/SEPEmptyException.java
  src/main/java/exceptions/SEPException.java
  src/main/java/exceptions/SEPFormatException.java
  src/main/java/exceptions/SEPNotFoundException.java
  src/main/java/exceptions/SEPRangeException.java
  src/main/java/student/Student.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/UI.java
Labels: priority.High

#41 Allocator JUnit Test
  src/test/java/findoursep/AllocatorTest.java
Labels: priority.High

#43 Add JUnit testing for Parser and StudentList Classes
  src/main/java/allocator/Allocator.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/parser/Parser.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/UI.java
  src/test/java/parser/ParserTest.java
  src/test/java/studentlist/StudentListTest.java
Labels: priority.High

#45 Add JUnit testing for UI class
  src/main/java/findoursep/FindOurSEP.java
  src/test/java/ui/UITest.java
Labels: priority.High

#47 JUnit for Student and University package
  src/test/java/student/StudentTest.java
  src/test/java/university/UniversityTest.java
Labels: priority.Low, severity.Low

#57 Fix ListCommand logic flaw
  src/main/java/command/ListCommand.java
  src/main/java/parser/Parser.java
  src/main/java/studentlist/StudentList.java
Labels: type.Bug, priority.High

#53 First Criteria Iteration
  src/main/java/allocator/Allocator.java
  src/main/java/command/CriteriaCommand.java
  src/main/java/parser/Parser.java
  src/main/java/studentlist/StudentList.java
  src/test/java/findoursep/AllocatorTest.java
Labels: priority.Medium, severity.Low

#55 Add New Commands stats and viewQuota for V2.0 Iteration
  src/main/java/command/StatCommand.java
  src/main/java/command/ViewQuotaCommand.java
  src/main/java/exceptions/SEPFormatException.java
  src/main/java/exceptions/SEPNotFoundException.java
  src/main/java/parser/Parser.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/Messages.java
  src/test/java/parser/ParserTest.java
Labels: priority.High

#61 Add reading in different file type feature
  build.gradle
  docs/DeveloperGuide.md
  src/main/java/exceptions/SEPDuplicateException.java
  src/main/java/exceptions/SEPFormatException.java
  src/main/java/exceptions/SEPIOException.java
  src/main/java/exceptions/SEPNotFoundException.java
  src/main/java/exceptions/SEPUnknownException.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/UI.java
  test.csv
  test.json
  test.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#65 Enhancement: Replace commands with Enum
  src/main/java/command/Commands.java
  src/main/java/parser/Parser.java
Labels: priority.Medium

#67 Update DG for Parser class
  docs/DeveloperGuide.md
  docs/UML_Diagrams/ParserClass.drawio.svg
  docs/UML_Diagrams/ParserSequence.drawio.svg
Labels: priority.High

#69 Add Filter Feature
  src/main/java/allocator/Allocator.java
  src/main/java/command/Commands.java
  src/main/java/command/FilterCommand.java
  src/main/java/command/StatCommand.java
  src/main/java/command/ViewQuotaCommand.java
  src/main/java/exceptions/SEPEmptyException.java
  src/main/java/exceptions/SEPFormatException.java
  src/main/java/exceptions/SEPNotFoundException.java
  src/main/java/exceptions/SEPUnknownException.java
  src/main/java/parser/Parser.java
  src/main/java/storage/Storage.java
  src/main/java/studentlist/StudentList.java
  src/test/java/studentlist/StudentListTest.java
Labels: priority.High

#75 Update DG for Allocator class
  docs/DeveloperGuide.md
  docs/UML_Diagrams/AllocatorClass.drawio.svg
  docs/UML_Diagrams/AllocatorSequence.drawio.svg
  src/main/java/command/AllocateCommand.java
  src/main/java/ui/UI.java
Labels: priority.High

#76 Add revert command
  src/main/java/command/Commands.java
  src/main/java/command/RevertCommand.java
  src/main/java/parser/Parser.java
  src/main/java/student/Student.java
  src/main/java/studentlist/StudentList.java
  src/main/java/ui/Messages.java
  src/test/java/parser/ParserTest.java
Labels: type.Task, priority.High

#79 Refactor to improve code quality
  src/main/java/exceptions/SEPEmptyException.java
  src/main/java/exceptions/SEPIOException.java
  src/main/java/filehandler/FileHandler.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/ui/Messages.java
  src/main/java/ui/UI.java
  test.json
  test.txt
  test2.csv
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#80 DeveloperGuide.md: Add UI features
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UML_Diagrams/UIClass.drawio.svg
  docs/UML_Diagrams/Untitled Diagram.drawio
  docs/UserGuide.md
  docs/team/isaacsaw.md
Labels: type.Task, priority.Medium

#83 Set up saving of data pipeline
  src/main/java/filehandler/FileHandler.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/ui/UI.java
  src/test/java/parser/ParserTest.java
  src/test/java/ui/UITest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High

#87 Add save data in JSON & TXT format
  data/allocation_results.json
  data/allocation_results.txt
  src/main/java/filehandler/FileHandler.java
  test.txt
Labels: priority.High

#90 Add input and exit feature to user guide
  data/allocation_results.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ehz0ah.md
  src/main/java/filehandler/FileHandler.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/ui/UI.java
  test2.csv
Labels: priority.High

#94 Add Sequence diagram for find and filter commands
  docs/UML_Diagrams/FilterSequence.drawio.svg
  docs/UML_Diagrams/FilterStudentAllocationListsd.drawio.svg
  docs/UML_Diagrams/FilterStudentGpasd.drawio.svg
  docs/UML_Diagrams/FilterStudentIdsd.drawio.svg
  docs/UML_Diagrams/FilterStudentReportsd.drawio.svg
  docs/UML_Diagrams/FindSequence.drawio.svg
  docs/UML_Diagrams/GenerateReportsd.drawio.svg
  docs/UML_Diagrams/PrintStudentListsd.drawio.svg
Labels: priority.High

#97 Update DeveloperGuide.md according to comments
  docs/DeveloperGuide.md
  docs/UML_Diagrams/AddCommand.drawio.svg
  docs/UML_Diagrams/AllocatorSequence.drawio.svg
  docs/UML_Diagrams/DeleteCommand.drawio.svg
  docs/UML_Diagrams/GenerateCommandSequence.drawio.svg
  docs/UML_Diagrams/ParserSequence.drawio.svg
  docs/UML_Diagrams/UIClass.drawio.svg
  docs/UML_Diagrams/Untitled Diagram.drawio
Labels: priority.High

#99 UML diagrams for DG (Exit, Help & Unknown Commands)
  data/allocation_results.json
  docs/DeveloperGuide.md
  docs/UML_Diagrams/ExitSequence.drawio.svg
  docs/UML_Diagrams/FileHandlerSequence.drawio.svg
  src/main/java/exceptions/SEPEmptyException.java
  src/main/java/filehandler/FileHandler.java
  src/main/java/findoursep/FindOurSEP.java
  src/main/java/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High
