Repository AY2425S1-CS2113-W12-2/tp, pull requests merged in 2024-11, with the labels that each got.

#101 Update personal portfolio page for ehz0ah
  docs/DeveloperGuide.md
  docs/team/ehz0ah.md
  docs/team/johndoe.md
  docs/team/paulktham.md
Labels: priority.High

#102 Add Find and Filter commands to DG and UG, Update PPP
  docs/DeveloperGuide.md
  docs/UML_Diagrams/FilterStudentAllocationListsd.drawio.svg
  docs/UML_Diagrams/FilterStudentGpasd.drawio.svg
  docs/UML_Diagrams/FilterStudentReportsd.drawio.svg
  docs/UML_Diagrams/FindSequence.drawio.svg
  docs/UML_Diagrams/GenerateReportsd.drawio.svg
  docs/UML_Diagrams/PrintStudentListsd.drawio.svg
  docs/UserGuide.md
  docs/team/holy-an.md
  src/main/java/exceptions/SEPFormatException.java
  src/main/java/ui/Messages.java
Labels: priority.High

#107 GenerateReportsd: Add activation bars
  docs/UML_Diagrams/GenerateReportsd.drawio.svg
Labels: priority.High

#113 Refactor filter student report
  src/main/java/studentlist/StudentList.java
Labels: priority.High

#114 Fix RevertCommand bugs
  src/main/java/command/RevertCommand.java
  src/main/java/university/UniversityRepository.java
Labels: type.Bug, priority.High

#115 Add JUnit test for FileHandler Class
  data/allocation_results.csv
  data/allocation_results.json
  data/allocation_results.txt
  src/main/java/filehandler/FileHandler.java
  src/main/java/ui/UI.java
  src/test/java/filehandler/FileHandlerTest.java
  test.csv
  test.txt
  test.xml
Labels: priority.High, severity.High

#116 Fix CriteriaCommand bug
  src/main/java/allocator/Allocator.java
  src/main/java/exceptions/SEPFormatException.java
Labels: priority.High

#120 Enhance Developer Guide
  docs/DeveloperGuide.md
Labels: priority.Medium, severity.Medium

#122 Update to UG and DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/CSVFormat.png
  docs/images/JSONFormat.png
  docs/images/TXTFormat.png
  docs/images/ehz0ah.png
  src/main/java/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#123 Update DG
  docs/DeveloperGuide.md
  docs/UML_Diagrams/FileHandlerSequence.drawio.svg
  docs/UML_Diagrams/FileHandlerSequenceOld.drawio.svg
  docs/team/ehz0ah.md
Labels: priority.High

#127 Update codebase
  docs/UserGuide.md
  src/main/java/exceptions/SEPIOException.java
  src/main/java/exceptions/SEPUnknownException.java
  src/test/java/filehandler/FileHandlerTest.java
Labels: type.Task, type.Bug, priority.High

#130 Update UG, PPP, and AboutUs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/images/thisisxxz.jpg
  docs/team/thisisxxz.md
Labels: priority.Medium, severity.Medium

#133 Update DG
  data/allocation_results.csv
  data/allocation_results.json
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UML_Diagrams/FilterCommandClass.drawio.svg
  docs/UML_Diagrams/FindCommandClass.drawio.svg
  docs/UML_Diagrams/PrintStudentListsd.drawio.svg
  docs/UML_Diagrams/saveAllocationResultsSequence.drawio.svg
  docs/images/Catnaldo.jpeg
  docs/team/holy-an.md
Labels: priority.High

#134 Update UG
  docs/UserGuide.md
  src/main/java/ui/Messages.java
  src/main/java/ui/UI.java
Labels: priority.High

#135 Update UserGuide.md
  .gitignore
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/grincat.png
Labels: priority.High

#136 Fix formatting issues for UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#137 Increase test files input size
  test.csv
  test.json
Labels: priority.High

#174 Fix bugs from Dry PE
  docs/UserGuide.md
  src/main/java/ui/UI.java
Labels: type.Bug, priority.High, severity.Medium

#180 Fix Delete Bug
  src/main/java/studentlist/StudentList.java
Labels: priority.High

#182 Update UG
  docs/AboutUs.md
  docs/README.md
  docs/UserGuide.md
  docs/team/ehz0ah.md
  docs/team/holy-an.md
  docs/team/isaacsaw25.md
  docs/team/paulktham.md
  docs/team/thisisxxz.md
  src/main/java/ui/Messages.java
  src/main/java/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#183 Update UG
  docs/UserGuide.md
Labels: priority.Medium

#184 Fix table in Accepted File Format
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#185 Update table in UG
  docs/UserGuide.md
Labels: priority.Medium

#186 Add page break
  docs/UserGuide.md
  docs/team/ehz0ah.md
Labels: priority.High

#187 Adjust page break
  docs/UserGuide.md
  docs/team/ehz0ah.md
Labels: priority.High

#188 Adjust page breaks
  docs/UserGuide.md
Labels: priority.High

#189 small edits to Delete Command
  docs/UML_Diagrams/DeleteCommand.drawio.svg
Labels: priority.Medium

#191 Small fixes
  docs/DeveloperGuide.md
  docs/team/ehz0ah.md
Labels: priority.Medium

#193 Fix DG
  docs/DeveloperGuide.md
Labels: priority.Medium

#198 last fix to deletecommand diagram
  docs/UML_Diagrams/DeleteCommand.drawio.svg
Labels: priority.Low

#200 Update ppp
  docs/team/ehz0ah.md
Labels: priority.Medium

#201 Update UG
  docs/UserGuide.md
Labels: priority.Medium

#202 Adjust page break
  docs/UserGuide.md
Labels: priority.Medium

#203 Adjust UG
  docs/UserGuide.md
Labels: priority.Medium
